# Cluster Configuration

PRIMARY_CLUSTER_NAME="k8s-chaos-lab"
SECONDARY_CLUSTER_NAME="k8s-chaos-lab-2"
CLUSTER_NAMES=("${PRIMARY_CLUSTER_NAME}" "${SECONDARY_CLUSTER_NAME}")
CLUSTER_NAME="${PRIMARY_CLUSTER_NAME}"
AWS_REGION="us-east-1"
NODE_COUNT="2"
NODE_TYPE="t3.small"
USE_SPOT="true"